project_id = "txuptwgqziperdffnuqq"

[functions.get-google-maps-key]
verify_jwt = false

[functions.get-mapbox-token]
verify_jwt = false

[functions.send-message-notification]
verify_jwt = false

[functions.create-credit-payment]
verify_jwt = true

[functions.process-credit-payment]
verify_jwt = false