import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'en' | 'it';

interface LanguageContextType {
  language: Language;
  setLanguage: (language: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  en: {
    // Header
    'header.favorites': 'Favorites',
    'header.signOut': 'Sign Out',
    'header.signIn': 'Sign In',
    'header.postListing': 'Post Listing',
    'header.getStarted': 'Get Started',
    'header.publishListings': 'Publish Listings',
    'header.myListings': 'My Listings',
    'header.messages': 'Messages',
    'header.about': 'About Us',
    'header.profile': 'Profile',
    'header.profileInfo': 'Profile Information',
    'header.language': 'Language',
    'header.hello': 'Hello',
    'header.logIn': 'Log In',
    'header.start': 'Start',
    'header.account': 'Account',
    
    // Languages
    'language.english': 'English',
    'language.italian': 'Italian',
    
    // About Page
    'about.title': 'About Us',
    'about.backHome': 'Back Home',
    'about.intro1': 'Tired of the low quality of real estate services in Milan, we decided to build a platform to make it safer and easier for students who move to University to find a place to live.',
    'about.intro2': 'We carefully select the real estate companies and landowners who share their announcements on this platform based on various criteria–quality-price ratio, responsiveness, comfort–in order to reduce the stress of students as much as possible. We also make sure that only students can make purchases on this platform in order to protect landowners. Enjoy the website and good luck finding your perfect home!',
    'about.founders': 'Melchior and Teo',
    'about.contactInfo': 'Contact Information',
    'about.email': 'Email:',
    'about.partnerTitle': 'Want to partner with us?',
    'about.partnerText': 'Write at',
    'about.partnerOr': 'or schedule a meeting right now',
    'about.scheduleMeeting': 'Schedule Meeting',
    
    // Homepage
    'home.heroWelcome': 'Welcome back',
    'home.heroTitle': 'Your perfect student home here and now.',
    'home.heroSubtitle': 'Connecting students with verified housing near Bocconi University and other top Milan universities. Trusted by agencies, loved by students.',
    'home.heroSubtitleStudent': 'Ready to find your perfect student accommodation?',
    'home.heroSubtitleRealtor': 'Manage your listings and connect with potential tenants.',
    'home.findPlace': 'Find a Place',
    'home.universitiesTitle': 'Perfect for students near leading universities.',
    'home.universitiesSubtitle': 'Find housing within walking distance or easy commute to Milan\'s best universities',
    'home.featuredTitle': 'Featured Properties',
    'home.featuredSubtitle': 'Hand-picked accommodations from trusted agencies',
    'home.featured': 'Featured',
    'home.month': '/month',
    'home.viewDetails': 'View Details',
    'home.viewAll': 'View All Properties',
    'home.quickActions': 'Quick Actions',
    'home.quickActionsSubtitle': 'Access your most important features',
    'home.messages': 'Messages',
    'home.messagesDesc': 'Chat with landlords and agencies',
    'home.messagesDescRealtor': 'Chat with potential tenants',
    'home.savedListings': 'Saved Listings',
    'home.savedListingsDesc': 'View your favorite properties',
    'home.explore': 'Explore',
    'home.exploreDesc': 'Discover new properties',
    'home.addListing': 'Add Listing',
    'home.addListingDesc': 'Create a new property listing',
    'home.myListings': 'My Listings',
    'home.myListingsDesc': 'View and manage your properties',
    'home.analytics': 'Analytics',
    'home.analyticsDesc': 'View listing performance',
    'home.recentActivity': 'Recent Activity',
    'home.recentActivityDesc': 'No recent activity yet. Start exploring to see your activity here!',
    'home.dashboardStats': 'Dashboard Stats',
    'home.dashboardStatsDesc': 'Overview of your listing performance',
    'home.activeListings': 'Active Listings',
    'home.totalViews': 'Total Views',
    'home.inquiries': 'Inquiries',
    'home.needHelp': 'Need Help?',
    'home.contactUs': 'Contact us at teodor.cosmovici@studbocconi.it',
    'home.helpDesc': 'We are here to help you with anything you need. We answer in 24 hours or less.',
    'home.quickActionsRealtorSubtitle': 'Manage your property listings and business',
    
    // Benefits Section
    'home.whyChooseTitle': 'Why choose flat2study?',
    'home.whyChooseSubtitle': 'We make finding student accommodation in Milan safe, easy, and reliable.',
    'home.verifiedProperties': 'Verified Properties',
    'home.verifiedPropertiesDesc': 'All properties are verified and listed by trusted agencies and landlords.',
    'home.studentOnly': 'Student-Only',
    'home.studentOnlyDesc': 'Exclusive platform for students, ensuring the best experience for all users.',
    'home.perfectLocations': 'Perfect Locations',
    'home.perfectLocationsDesc': 'Properties near top Milan universities with easy commute options.',
    
    'addYourListings': 'Add Your Listing',
    
    // Auth Page
    'auth.backToHome': 'Back to Home',
    'auth.title': 'Log In to Flat2Study',
    'auth.description': 'Access your account to manage your listings and messages',
    'auth.checkingAuth': 'Checking authentication...',
    'auth.email': 'Email',
    'auth.emailPlaceholder': 'your.email@example.com',
    'auth.password': 'Password',
    'auth.passwordPlaceholder': 'Enter your password',
    'auth.logIn': 'Log In',
    'auth.forgotPassword': 'Forgot your password?',
    'auth.resetTitle': 'Reset your password',
    'auth.resetDescription': 'Enter your email address and we\'ll send you a link to reset your password.',
    'auth.sendResetEmail': 'Send Reset Email',
    'auth.backToLogin': 'Back to log in',
    'auth.noAccount': 'Don\'t have an account?',
    'auth.getStarted': 'Get started here',
    'auth.passwordsNoMatch': 'Passwords do not match',
    'auth.passwordTooShort': 'Password must be at least 6 characters long',
    'auth.accountExists': 'An account with this email already exists. Please log in instead.',
    'auth.createFailed': 'Failed to create account',
    'auth.accountCreated': 'Account created successfully! Please check your email to verify your account.',
    'auth.loginFailed': 'Failed to log in',
    'auth.resetFailed': 'Failed to send reset email',
    'auth.resetSuccess': 'Password reset email sent! Check your inbox and follow the instructions.',
    
    // User Type Selection
    'userType.backToHome': 'Back to Home',
    'userType.title': 'Get Started with Flat2Study',
    'userType.description': 'Choose your profile type to create an account',
    'userType.realtorTitle': 'For property manager, real estate agency and company',
    'userType.realtorDescription': 'Real estate professionals managing multiple properties',
    'userType.realtorFeatures': 'List and manage properties, connect with potential tenants, track inquiries',
    'userType.privateTitle': 'For private landlords and property managers',
    'userType.privateDescription': 'Individual property owners renting their properties',
    'userType.privateFeatures': 'List and manage properties, connect with potential tenants, track inquiries',
    'userType.studentTitle': 'For Apartment Seekers',
    'userType.studentDescription': 'Students looking for accommodation',
    'userType.studentFeatures': 'Search properties, save favorites, request viewings, connect with landlords',
    'userType.getStarted': 'Get Started',
    'userType.alreadyAccount': 'Already have an account?',
    'userType.logInHere': 'Log in here',
    
    // Signup Student
    'signup.student.backToSelection': 'Back to Selection',
    'signup.student.title': 'Student Registration',
    'signup.student.description': 'Create your account to start searching for accommodations',
    'signup.student.profilePicture': 'Profile Picture',
    'signup.student.uploadPhoto': 'Upload Photo',
    'signup.student.name': 'Name',
    'signup.student.surname': 'Surname',
    'signup.student.namePlaceholder': 'First name',
    'signup.student.surnamePlaceholder': 'Last name',
    'signup.student.phone': 'Phone Number',
    'signup.student.phonePlaceholder': '+39 123 456 7890',
    'signup.student.university': 'University',
    'signup.student.universityPlaceholder': 'Select your university',
    'signup.student.selectUniversity': 'Please select your university',
    'signup.student.email': 'Email',
    'signup.student.passwordCreate': 'Create a password (min. 6 characters)',
    'signup.student.confirmPassword': 'Confirm Password',
    'signup.student.confirmPasswordPlaceholder': 'Confirm your password',
    'signup.student.createAccount': 'Create Student Account',
    'signup.student.alreadyHaveAccount': 'Already have an account?',
    'signup.student.logInHere': 'Log in here',
    
    // Signup Realtor
    'signup.realtor.title': 'Realtor Registration',
    'signup.realtor.description': 'Create your professional account to start listing properties',
    'signup.realtor.emailPlaceholder': 'your.email@company.com',
    'signup.realtor.company': 'Company',
    'signup.realtor.companyPlaceholder': 'Real Estate Agency Name',
    'signup.realtor.license': 'License Number',
    'signup.realtor.licensePlaceholder': 'Professional license number',
    'signup.realtor.createAccount': 'Create Realtor Account',
    
    // Signup Private
    'signup.private.title': 'Private Individual Registration',
    'signup.private.description': 'Create your account to start listing your property',
    'signup.private.birthDate': 'Birth Date',
    'signup.private.codiceFiscale': 'Codice Fiscale',
    'signup.private.codiceFiscalePlaceholder': 'RSSMRA80A01H501Z',
    'signup.private.createAccount': 'Create Account',
    
    // Universities
    'university.bocconi': 'Bocconi University',
    'university.politecnico': 'Politecnico di Milano',
    'university.cattolica': 'Università Cattolica del Sacro Cuore',
    'university.statale': 'Università Statale',
    'university.other': 'Another University',
    
    // Search Page
    'search.placeholder': 'Search by location, university, or amenities...',
    'search.sortBy': 'Sort by:',
    'search.relevance': 'Relevance',
    'search.priceLowHigh': 'Price: Low to High',
    'search.priceHighLow': 'Price: High to Low',
    'search.newest': 'Newest First',
    'search.distance': 'Distance',
    'search.loading': 'Loading listings...',
    'search.propertiesInView': 'properties in current view',
    'search.noPropertiesView': 'No properties in current view.',
    'search.moveMap': 'Move the map to see listings in different areas',
    'search.noResults': 'No properties match your search criteria.',
    'search.clearFilters': 'Clear Filters',
    
    // Profile Page
    'profile.back': 'Back',
    'profile.about': 'About',
    'profile.agency': 'Agency',
    'profile.student': 'Student',
    'profile.tellAbout': 'Tell us about yourself...',
    'profile.characters': 'characters',
    'profile.cancel': 'Cancel',
    'profile.save': 'Save',
    'profile.saving': 'Saving...',
    'profile.noDescription': 'No description added yet. Click the edit button to add one.',
    'profile.contact': 'Contact',
    'profile.contactInformation': 'Contact Information',
    'profile.memberSince': 'Member since',
    'profile.pleaseSignIn': 'Please sign in to view your profile.',
    
    // Common
    'common.email': 'Email',
    'common.phone': 'Phone',
    'common.address': 'Address',
    'common.city': 'City',
    'common.country': 'Country',
    'common.price': 'Price',
    'common.bedrooms': 'Bedrooms',
    'common.bathrooms': 'Bathrooms',
    'common.furnished': 'Furnished',
    'common.available': 'Available',
    'common.contact': 'Contact',
    'common.viewDetails': 'View Details',
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.success': 'Success',
    'common.back': 'Back',
    'common.send': 'Send',
    'common.sending': 'Sending...',
    'common.select': 'Select',
    'common.cancel': 'Cancel',
    'common.save': 'Save',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.create': 'Create',
    'common.update': 'Update',
    'common.view': 'View',
    
    // Listing Details
    'listing.backToSearch': 'Back to Search',
    'listing.sendMessage': 'Send Message',
    'listing.messageSent': 'Message Sent',
    'listing.messageSentDesc': 'Your message has been sent to the agency',
    'listing.messageError': 'Failed to send message. Please try again.',
    'listing.loadingDetails': 'Loading listing details...',
    'listing.notFound': 'Listing not found',
    'listing.authRequired': 'Authentication Required',
    'listing.authRequiredDesc': 'Please log in to send a message',
    'listing.messageRequired': 'Message Required',
    'listing.messageRequiredDesc': 'Please enter a message',
    'listing.agencyContact': 'Agency Contact',
    'listing.location': 'Location',
    'listing.amenities': 'Amenities',
    'listing.description': 'Description',
    'listing.perMonth': 'per month',
    'listing.deposit': 'deposit',
    'listing.agencyFee': 'Agency Fee',
    'listing.availableFrom': 'Available from',
    'listing.furnished': 'Furnished',
    'listing.billsIncluded': 'Bills Included',
    'listing.floor': 'Floor',
    'listing.noImages': 'No images available',
    'listing.bedroom': 'bedroom',
    'listing.bedrooms': 'bedrooms',
    'listing.bathroom': 'bathroom',
    'listing.bathrooms': 'bathrooms',
    'listing.messageDefault': 'Hello, I am interested in your listing. Could I have more information?',
    'listing.enterMessage': 'Enter your message...',
    
    // Property Types
    'propertyType.room': 'Room',
    'propertyType.studio': 'Studio',
    'propertyType.apartment': 'Apartment',
    'propertyType.flat': 'Flat',
    
    // Messages
    'messages.title': 'Messages',
    'messages.loadingMessages': 'Loading messages...',
    'messages.selectConversation': 'Select a conversation',
    'messages.selectConversationDesc': 'Choose a conversation from the list to view messages',
    'messages.manageTenantInquiries': 'Manage inquiries from potential tenants',
    'messages.conversationsWithAgencies': 'Your conversations with property agencies',
    'messages.messageSent': 'Message sent',
    'messages.messageSentDesc': 'Your message has been sent successfully.',
    'messages.messageError': 'Failed to send message. Please try again.',
    'messages.typeReply': 'Type your reply...',
    'messages.typeMessage': 'Type your message...',
    'messages.noConversationsYet': 'No conversations yet',
    'messages.noConversationsDesc': 'When students send inquiries about your listings, they\'ll appear here.',
    'messages.backToHome': 'Back to home',

    // My Listings
    'myListings.title': 'My Listings',
    'myListings.subtitle': 'Manage your property listings',
    'myListings.totalCount': 'total',
    'myListings.addNewListing': 'Add New Listing',
    'myListings.noListingsTitle': 'No listings yet',
    'myListings.noListingsDescription': 'Start by creating your first property listing',
    'myListings.createFirstListing': 'Create Your First Listing',
    'myListings.loadingListings': 'Loading your listings...',
    'myListings.perMonth': 'per month',
    'myListings.actions.view': 'View',
    'myListings.actions.edit': 'Edit',
    'myListings.actions.delete': 'Delete',
    'myListings.deleteConfirm': 'Are you sure you want to delete this listing?',
    'myListings.deleteSuccess': 'Listing deleted successfully',
    'myListings.deleteError': 'Failed to delete listing',
    'myListings.loadError': 'Failed to load your listings',
    'myListings.status.published': 'Published',
    'myListings.status.draft': 'Draft',
    'myListings.status.expired': 'Expired',
    'myListings.status.archived': 'Archived',

    // Favorites
    'favorites.title': 'My Favorites',
    'favorites.backToSearch': 'Back to Search',
    'favorites.savedListings': 'Your saved listings',
    'favorites.loadingFavorites': 'Loading your favorites...',
    'favorites.noFavoritesYet': 'No favorites yet',
    'favorites.noFavoritesDesc': 'Start browsing listings and save the ones you like by clicking the heart icon.',
    'favorites.browseListings': 'Browse Listings',
    'favorites.listingSaved': 'listing',
    'favorites.listingsSaved': 'listings',
    'favorites.saved': 'saved',
    
    // Create Listing
    'createListing.title': 'Create New Listing',
    'createListing.subtitle': 'Add a new property to your portfolio',
    'createListing.back': 'Back',
    'createListing.basicInfo': 'Basic Information',
    'createListing.propertyTitle': 'Property Title',
    'createListing.titlePlaceholder': 'e.g. Cozy Studio near University',
    'createListing.propertyType': 'Property Type',
    'createListing.selectType': 'Select type',
    'createListing.description': 'Description',
    'createListing.descriptionPlaceholder': 'Describe your property, its features, and what makes it special...',
    'createListing.propertyImages': 'Property Images',
    'createListing.uploadImages': 'Upload Images',
    'createListing.location': 'Location',
    'createListing.address': 'Address',
    'createListing.addressPlaceholder': 'e.g. Via Roma 123',
    'createListing.city': 'City',
    'createListing.cityPlaceholder': 'e.g. Milan',
    'createListing.country': 'Country',
    'createListing.countryPlaceholder': 'e.g. Italy',
    'createListing.pricingDetails': 'Pricing & Details',
    'createListing.monthlyRent': 'Monthly Rent (EUR)',
    'createListing.deposit': 'Deposit (EUR)',
    'createListing.bedrooms': 'Bedrooms',
    'createListing.bathrooms': 'Bathrooms',
    'createListing.floor': 'Floor',
    'createListing.floorPlaceholder': 'e.g. 2nd floor',
    'createListing.size': 'Size (sqm)',
    'createListing.agencyFee': 'Agency Fee',
    'createListing.agencyFeePlaceholder': 'e.g. One month rent or percentage',
    'createListing.furnished': 'Furnished',
    'createListing.billsIncluded': 'Bills Included',
    'createListing.amenities': 'Amenities',
    'createListing.availability': 'Availability',
    'createListing.availableFrom': 'Available From',
    'createListing.create': 'Create Listing',
    'createListing.cancel': 'Cancel',
    'createListing.creating': 'Creating...',
    'createListing.missingInfo': 'Missing Information',
    'createListing.pleaseProvideRequired': 'Please provide all required information',
    'createListing.error': 'Error',
    'createListing.success': 'Success',
    'createListing.listingCreated': 'Listing created successfully!',
    
    // Amenities
    'amenities.wifi': 'WiFi',
    'amenities.washingMachine': 'Washing Machine',
    'amenities.dishwasher': 'Dishwasher',
    'amenities.parking': 'Parking',
    'amenities.balcony': 'Balcony',
    'amenities.garden': 'Garden',
    'amenities.gym': 'Gym',
    'amenities.swimmingPool': 'Swimming Pool',
    'amenities.airConditioning': 'Air Conditioning',
    'amenities.heating': 'Heating',
    
    // Filters
    'filters.price': 'Price',
    'filters.priceRange': 'Price Range (Monthly)',
    'filters.type': 'Type',
    'filters.propertyType': 'Property Type',
    'filters.availableFrom': 'Available From',
    'filters.nearUniversity': 'Near University',
    'filters.university': 'University',
    'filters.selectUniversity': 'Select university',
    'filters.anyUniversity': 'Any university',
    'filters.bedrooms': 'Bedrooms',
    'filters.any': 'Any',
    'filters.bedroom': 'bedroom',
    'filters.bedroomsPlural': 'bedrooms',
    'filters.bedroomsPlus': '3+ bedrooms',
    'filters.furnished': 'Furnished',
    'filters.amenities': 'Amenities',
    'filters.clearAll': 'Clear all',
    'filters.filters': 'Filters',
    'filters.searchFilters': 'Search Filters',
    'filters.sortBy': 'Sort By',
    'filters.sort': 'Sort',
    'filters.types': 'types',
    'filters.amenitiesCount': 'amenities',
  },
  it: {
    // Header
    'header.favorites': 'Preferiti',
    'header.signOut': 'Esci',
    'header.signIn': 'Accedi',
    'header.postListing': 'Pubblica Annuncio',
    'header.getStarted': 'Inizia',
    'header.publishListings': 'Pubblica Annunci',
    'header.myListings': 'I Miei Annunci',
    'header.messages': 'Messaggi',
    'header.about': 'Chi Siamo',
    'header.profile': 'Profilo',
    'header.profileInfo': 'Informazioni Profilo',
    'header.language': 'Lingua',
    'header.hello': 'Ciao',
    'header.logIn': 'Accedi',
    'header.start': 'Inizia',
    'header.account': 'Account',
    
    // Languages
    'language.english': 'Inglese',
    'language.italian': 'Italiano',
    
    // About Page
    'about.title': 'Chi Siamo',
    'about.backHome': 'Torna alla Home',
    'about.intro1': 'Stanchi della bassa qualità dei servizi immobiliari a Milano, abbiamo deciso di costruire una piattaforma per rendere più sicuro e facile per gli studenti che si trasferiscono all\'Università trovare un posto dove vivere.',
    'about.intro2': 'Selezioniamo attentamente le società immobiliari e i proprietari di case che condividono i loro annunci su questa piattaforma basandoci su vari criteri: rapporto qualità-prezzo, reattività, comfort, al fine di ridurre il più possibile lo stress degli studenti. Ci assicuriamo anche che solo gli studenti possano effettuare acquisti su questa piattaforma per proteggere i proprietari. Godetevi il sito web e buona fortuna nel trovare la vostra casa perfetta!',
    'about.founders': 'Melchior e Teo',
    'about.contactInfo': 'Informazioni di Contatto',
    'about.email': 'Email:',
    'about.partnerTitle': 'Vuoi collaborare con noi?',
    'about.partnerText': 'Scrivi a',
    'about.partnerOr': 'o programma un incontro subito',
    'about.scheduleMeeting': 'Programma Incontro',
    
    // Homepage
    'home.heroWelcome': 'Bentornato',
    'home.heroTitle': 'La tua casa studentesca perfetta, ora e qui!',
    'home.heroSubtitle': 'Colleghiamo gli studenti a alloggi verificati vicino all\'Università Bocconi e alle altre principali università di Milano. Scelto dalle agenzie, amato dagli studenti.',
    'home.heroSubtitleStudent': 'Pronto a trovare il tuo alloggio perfetto per studenti?',
    'home.heroSubtitleRealtor': 'Gestisci i tuoi annunci immobiliari e la tua attività con efficacia.',
    'home.findPlace': 'Trova un Alloggio',
    'home.universitiesTitle': 'Ideale per studenti delle università d\'eccellenza.',
    'home.universitiesSubtitle': 'Trova alloggi a distanza pedonale o con facile collegamento alle migliori università di Milano',
    'home.featuredTitle': 'Proprietà in Evidenza',
    'home.featuredSubtitle': 'Alloggi selezionati da agenzie di fiducia',
    'home.featured': 'In Evidenza',
    'home.month': '/mese',
    'home.viewDetails': 'Vedi Dettagli',
    'home.viewAll': 'Vedi Tutte le Proprietà',
    'home.quickActions': 'Azioni Rapide',
    'home.quickActionsSubtitle': 'Accedi alle tue funzioni più importanti',
    'home.messages': 'Messaggi',
    'home.messagesDesc': 'Chatta con proprietari e agenzie',
    'home.messagesDescRealtor': 'Chatta con inquilini potenziali',
    'home.savedListings': 'Annunci Salvati',
    'home.savedListingsDesc': 'Visualizza le tue proprietà preferite',
    'home.explore': 'Esplora',
    'home.exploreDesc': 'Scopri nuove proprietà',
    'home.addListing': 'Aggiungi Annuncio',
    'home.addListingDesc': 'Crea un nuovo annuncio immobiliare',
    'home.myListings': 'I Miei Annunci',
    'home.myListingsDesc': 'Visualizza e gestisci le tue proprietà',
    'home.analytics': 'Analisi',
    'home.analyticsDesc': 'Visualizza le prestazioni degli annunci',
    'home.recentActivity': 'Attività Recente',
    'home.recentActivityDesc': 'Nessuna attività recente ancora. Inizia a esplorare per vedere la tua attività qui!',
    'home.dashboardStats': 'Statistiche Dashboard',
    'home.dashboardStatsDesc': 'Panoramica delle prestazioni dei tuoi annunci',
    'home.activeListings': 'Annunci Attivi',
    'home.totalViews': 'Visualizzazioni Totali',
    'home.inquiries': 'Richieste',
    'home.needHelp': 'Hai Bisogno di Aiuto?',
    'home.contactUs': 'Contattaci a teodor.cosmovici@studbocconi.it',
    'home.helpDesc': 'Siamo qui per aiutarti con tutto quello di cui hai bisogno. Rispondiamo entro 24 ore o meno.',
    'home.quickActionsRealtorSubtitle': 'Gestisci i tuoi annunci immobiliari e il tuo business',
    
    // Benefits Section
    'home.whyChooseTitle': 'Perché scegliere Flat2Study?',
    'home.whyChooseSubtitle': 'Rendiamo la ricerca di un alloggio per studenti a Milano sicura, semplice e affidabile.',
    'home.verifiedProperties': 'Proprietà Verificate',
    'home.verifiedPropertiesDesc': 'Tutti gli alloggi sono verificati e pubblicati da agenzie e proprietari di fiducia.',
    'home.studentOnly': 'Solo per Studenti',
    'home.studentOnlyDesc': 'Una piattaforma esclusiva per studenti, che garantisce la migliore esperienza a tutti gli utenti.',
    'home.perfectLocations': 'Posizioni Perfette',
    'home.perfectLocationsDesc': 'Alloggi vicino alle principali università di Milano, con comode opzioni di trasporto.',
    
    'addYourListings': 'Pubblica Il Tuo Annuncio',
    
    // Auth Page
    'auth.backToHome': 'Torna alla Home',
    'auth.title': 'Accedi a Flat2Study',
    'auth.description': 'Accedi al tuo account per gestire i tuoi annunci e messaggi',
    'auth.checkingAuth': 'Verifica autenticazione...',
    'auth.email': 'Email',
    'auth.emailPlaceholder': 'tua.email@esempio.com',
    'auth.password': 'Password',
    'auth.passwordPlaceholder': 'Inserisci la tua password',
    'auth.logIn': 'Accedi',
    'auth.forgotPassword': 'Hai dimenticato la password?',
    'auth.resetTitle': 'Reimposta la tua password',
    'auth.resetDescription': 'Inserisci il tuo indirizzo email e ti invieremo un link per reimpostare la password.',
    'auth.sendResetEmail': 'Invia Email di Reset',
    'auth.backToLogin': 'Torna al login',
    'auth.noAccount': 'Non hai un account?',
    'auth.getStarted': 'Inizia qui',
    'auth.passwordsNoMatch': 'Le password non corrispondono',
    'auth.passwordTooShort': 'La password deve essere lunga almeno 6 caratteri',
    'auth.accountExists': 'Un account con questa email esiste già. Effettua l\'accesso invece.',
    'auth.createFailed': 'Impossibile creare l\'account',
    'auth.accountCreated': 'Account creato con successo! Controlla la tua email per verificare l\'account.',
    'auth.loginFailed': 'Impossibile effettuare l\'accesso',
    'auth.resetFailed': 'Impossibile inviare l\'email di reset',
    'auth.resetSuccess': 'Email di reset password inviata! Controlla la tua casella e segui le istruzioni.',
    
    // User Type Selection
    'userType.backToHome': 'Torna alla Home',
    'userType.title': 'Inizia con Flat2Study',
    'userType.description': 'Scegli il tipo di profilo per creare un account',
    'userType.realtorTitle': 'Per property manager, agenzia immobiliare e azienda',
    'userType.realtorDescription': 'Professionisti del settore immobiliare che gestiscono più proprietà',
    'userType.realtorFeatures': 'Elenca e gestisci proprietà, connettiti con potenziali inquilini, monitora le richieste',
    'userType.privateTitle': 'Per proprietario privato',
    'userType.privateDescription': 'Proprietari individuali che affittano le loro proprietà',
    'userType.privateFeatures': 'Elenca e gestisci proprietà, connettiti con potenziali inquilini, monitora le richieste',
    'userType.studentTitle': 'Per Chi Cerca Casa',
    'userType.studentDescription': 'Studenti alla ricerca di un alloggio',
    'userType.studentFeatures': 'Cerca proprietà, salva i preferiti, richiedi visite, connettiti con i proprietari',
    'userType.getStarted': 'Inizia',
    'userType.alreadyAccount': 'Hai già un account?',
    'userType.logInHere': 'Accedi qui',
    
    // Signup Student
    'signup.student.backToSelection': 'Torna alla Selezione',
    'signup.student.title': 'Registrazione Studente',
    'signup.student.description': 'Crea il tuo account per iniziare a cercare alloggi',
    'signup.student.profilePicture': 'Foto Profilo',
    'signup.student.uploadPhoto': 'Carica Foto',
    'signup.student.name': 'Nome',
    'signup.student.surname': 'Cognome',
    'signup.student.namePlaceholder': 'Nome',
    'signup.student.surnamePlaceholder': 'Cognome',
    'signup.student.phone': 'Numero di Telefono',
    'signup.student.phonePlaceholder': '+39 123 456 7890',
    'signup.student.university': 'Università',
    'signup.student.universityPlaceholder': 'Seleziona la tua università',
    'signup.student.selectUniversity': 'Seleziona la tua università',
    'signup.student.email': 'Email',
    'signup.student.passwordCreate': 'Crea una password (min. 6 caratteri)',
    'signup.student.confirmPassword': 'Conferma Password',
    'signup.student.confirmPasswordPlaceholder': 'Conferma la tua password',
    'signup.student.createAccount': 'Crea Account Studente',
    'signup.student.alreadyHaveAccount': 'Hai già un account?',
    'signup.student.logInHere': 'Accedi qui',
    
    // Signup Realtor
    'signup.realtor.title': 'Registrazione Agente Immobiliare',
    'signup.realtor.description': 'Crea il tuo account professionale per iniziare a pubblicare proprietà',
    'signup.realtor.emailPlaceholder': 'tua.email@azienda.com',
    'signup.realtor.company': 'Azienda',
    'signup.realtor.companyPlaceholder': 'Nome Agenzia Immobiliare',
    'signup.realtor.license': 'Numero Licenza',
    'signup.realtor.licensePlaceholder': 'Numero licenza professionale',
    'signup.realtor.createAccount': 'Crea Account Agente',
    
    // Signup Private
    'signup.private.title': 'Registrazione Privato',
    'signup.private.description': 'Crea il tuo account per iniziare a pubblicare la tua proprietà',
    'signup.private.birthDate': 'Data di Nascita',
    'signup.private.codiceFiscale': 'Codice Fiscale',
    'signup.private.codiceFiscalePlaceholder': 'RSSMRA80A01H501Z',
    'signup.private.createAccount': 'Crea Account',
    
    // Universities
    'university.bocconi': 'Università Bocconi',
    'university.politecnico': 'Politecnico di Milano',
    'university.cattolica': 'Università Cattolica del Sacro Cuore',
    'university.statale': 'Università Statale',
    'university.other': 'Altra Università',
    
    // Search Page
    'search.placeholder': 'Cerca per posizione, università o servizi...',
    'search.sortBy': 'Ordina per:',
    'search.relevance': 'Rilevanza',
    'search.priceLowHigh': 'Prezzo: Dal Basso all\'Alto',
    'search.priceHighLow': 'Prezzo: Dall\'Alto al Basso',
    'search.newest': 'Più Recenti Prima',
    'search.distance': 'Distanza',
    'search.loading': 'Caricamento annunci...',
    'search.propertiesInView': 'proprietà nella vista corrente',
    'search.noPropertiesView': 'Nessuna proprietà nella vista corrente.',
    'search.moveMap': 'Sposta la mappa per vedere annunci in aree diverse',
    'search.noResults': 'Nessuna proprietà corrisponde ai tuoi criteri di ricerca.',
    'search.clearFilters': 'Cancella Filtri',
    
    // Profile Page
    'profile.back': 'Indietro',
    'profile.about': 'Informazioni',
    'profile.agency': 'Agenzia',
    'profile.student': 'Studente',
    'profile.tellAbout': 'Raccontaci di te...',
    'profile.characters': 'caratteri',
    'profile.cancel': 'Annulla',
    'profile.save': 'Salva',
    'profile.saving': 'Salvando...',
    'profile.noDescription': 'Non hai ancora aggiunto una descrizione. Clicca su modifica per scriverne una.',
    'profile.contact': 'Contatta',
    'profile.contactInformation': 'Informazioni di Contatto',
    'profile.memberSince': 'Membro dal',
    'profile.pleaseSignIn': 'Effettua l\'accesso per visualizzare il tuo profilo.',
    
    // Common
    'common.email': 'Email',
    'common.phone': 'Telefono',
    'common.address': 'Indirizzo',
    'common.city': 'Città',
    'common.country': 'Paese',
    'common.price': 'Prezzo',
    'common.bedrooms': 'Camere da Letto',
    'common.bathrooms': 'Bagni',
    'common.furnished': 'Arredato',
    'common.available': 'Disponibile',
    'common.contact': 'Contatta',
    'common.viewDetails': 'Vedi Dettagli',
    'common.loading': 'Caricamento...',
    'common.error': 'Errore',
    'common.success': 'Successo',
    'common.back': 'Indietro',
    'common.send': 'Invia',
    'common.sending': 'Invio...',
    'common.select': 'Seleziona',
    'common.cancel': 'Annulla',
    'common.save': 'Salva',
    'common.delete': 'Elimina',
    'common.edit': 'Modifica',
    'common.create': 'Crea',
    'common.update': 'Aggiorna',
    'common.view': 'Visualizza',
    
    // Listing Details
    'listing.backToSearch': 'Torna alla Ricerca',
    'listing.sendMessage': 'Invia Messaggio',
    'listing.messageSent': 'Messaggio Inviato',
    'listing.messageSentDesc': 'Il tuo messaggio è stato inviato all\'agenzia',
    'listing.messageError': 'Impossibile inviare il messaggio. Riprova.',
    'listing.loadingDetails': 'Caricamento dettagli annuncio...',
    'listing.notFound': 'Annuncio non trovato',
    'listing.authRequired': 'Autenticazione Richiesta',
    'listing.authRequiredDesc': 'Effettua l\'accesso per inviare un messaggio',
    'listing.messageRequired': 'Messaggio Richiesto',
    'listing.messageRequiredDesc': 'Inserisci un messaggio',
    'listing.agencyContact': 'Contatto Agenzia',
    'listing.location': 'Posizione',
    'listing.amenities': 'Servizi',
    'listing.description': 'Descrizione',
    'listing.perMonth': 'al mese',
    'listing.deposit': 'deposito',
    'listing.agencyFee': 'Commissione Agenzia',
    'listing.availableFrom': 'Disponibile dal',
    'listing.furnished': 'Arredato',
    'listing.billsIncluded': 'Bollette Incluse',
    'listing.floor': 'Piano',
    'listing.noImages': 'Nessuna immagine disponibile',
    'listing.bedroom': 'camera da letto',
    'listing.bedrooms': 'camere da letto',
    'listing.bathroom': 'bagno',
    'listing.bathrooms': 'bagni',
    'listing.messageDefault': 'Ciao, sono interessato al vostro annuncio. Potreste darmi maggiori informazioni?',
    'listing.enterMessage': 'Inserisci il tuo messaggio...',
    
    // Property Types
    'propertyType.room': 'Camera',
    'propertyType.studio': 'Monolocale',
    'propertyType.apartment': 'Appartamento',
    'propertyType.flat': 'Appartamento',
    
    // Messages
    'messages.title': 'Messaggi',
    'messages.loadingMessages': 'Caricamento messaggi...',
    'messages.selectConversation': 'Seleziona una conversazione',
    'messages.selectConversationDesc': 'Scegli una conversazione dall\'elenco per visualizzare i messaggi',
    'messages.manageTenantInquiries': 'Gestisci le richieste degli inquilini potenziali',
    'messages.conversationsWithAgencies': 'Le tue conversazioni con le agenzie immobiliari',
    'messages.messageSent': 'Messaggio inviato',
    'messages.messageSentDesc': 'Il tuo messaggio è stato inviato con successo.',
    'messages.messageError': 'Impossibile inviare il messaggio. Riprova.',
    'messages.typeReply': 'Scrivi la tua risposta...',
    'messages.typeMessage': 'Scrivi il tuo messaggio...',
    'messages.noConversationsYet': 'Nessuna conversazione al momento',
    'messages.noConversationsDesc': 'Quando gli studenti invieranno richieste sui tuoi annunci, appariranno qui.',
    'messages.backToHome': 'Torna a casa',
    
    // My Listings
    'myListings.title': 'I Miei Annunci',
    'myListings.subtitle': 'Gestisci i tuoi annunci immobiliari',
    'myListings.totalCount': 'in totale',
    'myListings.addNewListing': 'Aggiungi Nuovo Annuncio',
    'myListings.noListingsTitle': 'Nessun annuncio ancora',
    'myListings.noListingsDescription': 'Inizia creando il tuo primo annuncio immobiliare',
    'myListings.createFirstListing': 'Crea il Tuo Primo Annuncio',
    'myListings.loadingListings': 'Caricamento annunci...',
    'myListings.perMonth': 'al mese',
    'myListings.actions.view': 'Visualizza',
    'myListings.actions.edit': 'Modifica',
    'myListings.actions.delete': 'Elimina',
    'myListings.deleteConfirm': 'Sei sicuro di voler eliminare questo annuncio?',
    'myListings.deleteSuccess': 'Annuncio eliminato con successo',
    'myListings.deleteError': 'Errore nell\'eliminazione dell\'annuncio',
    'myListings.loadError': 'Errore nel caricamento degli annunci',
    'myListings.status.published': 'Pubblicato',
    'myListings.status.draft': 'Bozza',
    'myListings.status.expired': 'Scaduto',
    'myListings.status.archived': 'Archiviato',
    
    // Favorites
    'favorites.title': 'I Miei Preferiti',
    'favorites.backToSearch': 'Torna alla Ricerca',
    'favorites.savedListings': 'I tuoi annunci salvati',
    'favorites.loadingFavorites': 'Caricamento preferiti...',
    'favorites.noFavoritesYet': 'Nessun preferito ancora',
    'favorites.noFavoritesDesc': 'Inizia a sfogliare gli annunci e salva quelli che ti piacciono cliccando l\'icona del cuore.',
    'favorites.browseListings': 'Sfoglia Annunci',
    'favorites.listingSaved': 'annuncio',
    'favorites.listingsSaved': 'annunci',
    'favorites.saved': 'salvati',
    
    // Create Listing
    'createListing.title': 'Crea Nuovo Annuncio',
    'createListing.subtitle': 'Aggiungi una nuova proprietà al tuo portfolio',
    'createListing.basicInfo': 'Informazioni di Base',
    'createListing.propertyTitle': 'Titolo Annuncio',
    'createListing.propertyType': 'Tipologia di Immobile',
    'createListing.selectType': 'Seleziona tipologia',
    'createListing.description': 'Descrizione',
    'createListing.descriptionPlaceholder': 'Descrivi il tuo immobile...',
    'createListing.propertyImages': 'Immagini della Proprietà',
    'createListing.uploadImages': 'Carica Immagini',
    'createListing.location': 'Posizione',
    'createListing.address': 'Indirizzo',
    'createListing.addressPlaceholder': 'Via / indirizzo',
    'createListing.city': 'Città',
    'createListing.cityPlaceholder': 'Città',
    'createListing.country': 'Paese',
    'createListing.countryPlaceholder': 'Paese',
    'createListing.pricingDetails': 'Prezzo & Dettagli',
    'createListing.monthlyRent': 'Affitto Mensile (EUR)',
    'createListing.deposit': 'Deposito (EUR)',
    'createListing.bedrooms': 'Camere da Letto',
    'createListing.bathrooms': 'Bagni',
    'createListing.floor': 'Piano',
    'createListing.floorPlaceholder': '2°',
    'createListing.size': 'Superficie (mq)',
    'createListing.agencyFee': 'Commissione Agenzia',
    'createListing.agencyFeePlaceholder': 'es. 500 EUR o 1 mese di affitto',
    'createListing.furnished': 'Arredato',
    'createListing.billsIncluded': 'Spese Incluse',
    'createListing.amenities': 'Servizi',
    'createListing.availability': 'Disponibilità',
    'createListing.availableFrom': 'Disponibile da',
    'createListing.create': 'Crea Annuncio',
    'createListing.creating': 'Creando...',
    'createListing.cancel': 'Annulla',
    'createListing.back': 'Indietro',
    
    // Amenities
    'amenities.wifi': 'WiFi',
    'amenities.washingMachine': 'Lavatrice',
    'amenities.dishwasher': 'Lavastoviglie',
    'amenities.parking': 'Parcheggio',
    'amenities.balcony': 'Balcone',
    'amenities.garden': 'Giardino',
    'amenities.gym': 'Palestra',
    'amenities.swimmingPool': 'Piscina',
    'amenities.airConditioning': 'Aria Condizionata',
    'amenities.heating': 'Riscaldamento',
    
    // Filters
    'filters.price': 'Prezzo',
    'filters.priceRange': 'Fascia di Prezzo (Mensile)',
    'filters.type': 'Tipo',
    'filters.propertyType': 'Tipo di Proprietà',
    'filters.availableFrom': 'Disponibile Dal',
    'filters.nearUniversity': 'Vicino all\'Università',
    'filters.university': 'Università',
    'filters.selectUniversity': 'Seleziona università',
    'filters.anyUniversity': 'Qualsiasi università',
    'filters.bedrooms': 'Camere da Letto',
    'filters.any': 'Qualsiasi',
    'filters.bedroom': 'camera da letto',
    'filters.bedroomsPlural': 'camere da letto',
    'filters.bedroomsPlus': '3+ camere da letto',
    'filters.furnished': 'Arredato',
    'filters.amenities': 'Servizi',
    'filters.clearAll': 'Cancella tutto',
    'filters.filters': 'Filtri',
    'filters.searchFilters': 'Filtri di Ricerca',
    'filters.sortBy': 'Ordina Per',
    'filters.sort': 'Ordina',
    'filters.types': 'tipi',
    'filters.amenitiesCount': 'servizi',
  }
};

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  // Initialize language from localStorage immediately to avoid flash of wrong language
  const getInitialLanguage = (): Language => {
    if (typeof window !== 'undefined') {
      const savedLanguage = localStorage.getItem('language') as Language;
      if (savedLanguage && (savedLanguage === 'en' || savedLanguage === 'it')) {
        return savedLanguage;
      }
    }
    return 'en';
  };

  const [language, setLanguageState] = useState<Language>(getInitialLanguage);

  const setLanguage = (newLanguage: Language) => {
    setLanguageState(newLanguage);
    localStorage.setItem('language', newLanguage);
  };

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations[typeof language]] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}